METRIC_AVG_TURNAROUND = "avg_turnaround"
METRIC_AVG_WAITING = "avg_waiting"
METRIC_AVG_RESPONSE = "avg_response"
METRIC_CPU_UTILIZATION = "cpu_utilization"
METRIC_THROUGHPUT = "throughput"

LOWER_IS_BETTER = (METRIC_AVG_TURNAROUND, METRIC_AVG_WAITING, METRIC_AVG_RESPONSE)
HIGHER_IS_BETTER = (METRIC_CPU_UTILIZATION, METRIC_THROUGHPUT)
COMPARISON_METRICS = LOWER_IS_BETTER + HIGHER_IS_BETTER
