from enum import StrEnum


class Event(StrEnum):
    ARRIVAL = "ARRIVAL"
    DISPATCH = "DISPATCH"
    PREEMPT = "PREEMPT"
    CPU_BURST_END = "CPU_BURST_END" # EVENTO EXTRA APOS IMPLEMENTAR BURST IO E IO_DONE
    IO_DONE = "IO_DONE"
    CONTEXT_SWITCH = "CONTEXT_SWITCH" # EVENTO EXTRA
    TERMINATE = "TERMINATE"
    IDLE = "IDLE"
